In [3]:
import pandas as pd

# Store Sales

## Objectives

- Predict the weekly sales for each store.

## Algorithms/Models

- Multiple Regression (Regression)
- Support Vector Machine (Regression)
- Random Forest (Regression)

## Data Consolidation

In [4]:
features = pd.read_csv('raw_files/features.csv')
stores = pd.read_csv('raw_files/stores.csv')
train = pd.read_csv('raw_files/train.csv')

In [14]:
data = pd.merge(left=train, right=stores, on=['Store'], how='left')
data = pd.merge(left=data, right=features, on=['Store', 'Date'], how='left')
data.to_csv('store_sales.csv', index=False)

## Data Preview

In [15]:
data = pd.read_csv('store_sales.csv')
data.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Type,Size,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_y
0,1,1,2010-02-05,24924.50,False,A,151315,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,1,2010-02-12,46039.49,True,A,151315,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,1,2010-02-19,41595.55,False,A,151315,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,1,2010-02-26,19403.54,False,A,151315,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,1,2010-03-05,21827.90,False,A,151315,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

## Data Dictionary

- Store = the store number
- Date = the week
- Temperature = average temperature in the region
- Fuel_Price = cost of fuel in the region
- MarkDown1-5 = anonymized data related to promotional markdowns that Walmart is running. MarkDown data is only available after Nov 2011, and is not available for all stores all the time. Any missing value is marked with an NA.
- CPI = the consumer price index
- Unemployment = the unemployment rate
- IsHoliday = whether the week is a special holiday week
- Dept = the department number
- Date = the week
- Weekly_Sales = sales for the given department in the given store
- Type = The type of the store
- Size = The size of the store

## Basic Literature

- Aras, S. et al. (2017). Comparative study on retail sales forecasting between single and combination methods. *Journal of Business Economics and Management , 18(5)*, 803-832. https://doi.org/10.3846/16111699.2017.1367324.
- Beheshti-Kashi, S. et al. (2014). A survey on retail sales forecasting and prediction in fashion markets. *Systems Science & Control Engineering, 3(1)*, 154-161. https://doi.org/10.1080/21642583.2014.999389.

## Source

https://www.kaggle.com/c/walmart-recruiting-store-sales-forecasting